// Login Page
export const LOGIN_FETCHING = 'LOGIN_FETCHING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout
export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_FETCHING = 'LOGOUT_FETCHING';

// Equipment search
export const EQUIPMENT_SEARCH_SUCCESS = 'EQUIPMENT_SEARCH_SUCCESS';
export const EQUIPMENT_SEARCH_FAILED = 'EQUIPMENT_SEARCH_FAILED';
export const EQUIPMENT_SEARCH_FETCHING = 'EQUIPMENT_SEARCH_FETCHING';
// Equipment deatil
export const EQUIPMENT_DETAIL_SUCCESS = 'EQUIPMENT_DETAIL_SUCCESS';
export const EQUIPMENT_DETAIL_FAILED = 'EQUIPMENT_DETAIL_FAILED';
export const EQUIPMENT_DETAIL_FETCHING = 'EQUIPMENT_DETAIL_FETCHING';
